/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
// kotlinc .\App.kt -d app.jar
//  kotlin -classpath .\App.jar AppKt

class App {
    val greeting: String
        get() {
            
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    
}
